/* Generated By:JavaCC: Do not edit this line. mncTreeConstants.java Version 5.0 */
package parser;

public interface mncTreeConstants {
	public int JJTSTART = 0;
	public int JJTTYPE = 1;
	public int JJTPROGRAM = 2;
	public int JJTSTATEBLOCK = 3;
	public int JJTSTATE = 4;
	public int JJTSEQSTATE = 5;
	public int JJTDECSTATE = 6;
	public int JJTASSSTATE = 7;
	public int JJTBREAKSTATE = 8;
	public int JJTBRANCHSTATE = 9;
	public int JJTSWITCHSTATE = 10;
	public int JJTIFSTATE = 11;
	public int JJTCONDITION = 12;
	public int JJTRELATION = 13;
	public int JJTLOGICALOPERATOR = 14;
	public int JJTLOOPSTATE = 15;
	public int JJTWHILESTATE = 16;
	public int JJTDOWHILESTATE = 17;
	public int JJTFORSTATE = 18;
	public int JJTAUTOAS = 19;
	public int JJTEXPRESSION = 20;
	public int JJTADDITIVEEXPRESSION = 21;
	public int JJTMULTIPLICATIVEEXPRESSION = 22;
	public int JJTUNARYEXPRESSION = 23;
	public int JJTFLOAT = 24;
	public int JJTIDENTIFIER = 25;
	public int JJTINTEGER = 26;

	public String[] jjtNodeName = { "Start", "type", "Program", "StateBlock", "State", "SeqState", "DecState",
			"AssState", "BreakState", "BranchState", "SwitchState", "IfState", "Condition", "Relation",
			"LogicalOperator", "LoopState", "WhileState", "DoWhileState", "ForState", "AutoAS", "Expression",
			"AdditiveExpression", "MultiplicativeExpression", "UnaryExpression", "Float", "Identifier", "Integer", };
}
/*
 * JavaCC - OriginalChecksum=4da13271a4c277670f0b864bcafd88b8 (do not edit this
 * line)
 */
